name: Bot CI

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/bot.yml'
      - 'project/bot/**'
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ./project

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bot

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn package -pl zhenya:bot -am
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ghcr.io/${{ github.actor }}/bot:latest ./bot
      - name: Push image
        run: docker push ghcr.io/${{ github.actor }}/bot:latest
