name: Scrapper CI

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/scrapper.yml'
      - 'project/scrapper/**'
      - 'project/link-parser/**'
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ./project

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: scrapper

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Docker
        run: sudo systemctl start docker
      - name: Build with Maven
        run: mvn package -pl zhenya:scrapper -am
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build -t ${{ env.REGISTRY }}/zhenyadudko/${{ env.IMAGE_NAME }}:latest ./scrapper
      - name: Push image
        run: docker push ${{ env.REGISTRY }}/zhenyadudko/${{ env.IMAGE_NAME }}:latest
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkstyle
        run: mvn -pl zhenya:scrapper -am checkstyle:check